resources:
  - ../../base

patchesStrategicMerge:
  - replicas.yaml

configMapGenerator:
  - name: mykustom-map
    env: config.properties

generatorOptions:
  disableNameSuffixHash: true  # Optional, prevents hashed suffix in ConfigMap name
